# Generated by Django 2.2.4 on 2019-08-07 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_auto_20190806_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='nicotina',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.Proveedor'),
        ),
    ]
