# Generated by Django 2.2.4 on 2019-08-11 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_auto_20190811_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventastock',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Stock'),
        ),
    ]
