# Generated by Django 2.2.4 on 2019-08-15 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ventas', '0005_auto_20190811_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlujoCaja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('accion', models.CharField(choices=[('M', 'Movimiento'), ('E', 'Egreso')], max_length=10)),
                ('de', models.CharField(max_length=10)),
                ('para', models.CharField(blank=True, max_length=10)),
                ('cantidad', models.FloatField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
